### ISSUE TITLE
Inconsistency for json objects

### ISSUE THREAD

**Issue by shreyajn** [snapsend/snapsend#30]

**Comment by shreyajn** [comment]
envelopeName
recipientName
senderName
username
email 
password1
password2
profilepic
handle
imageId
url
filename
action 
dnum
token 
success
error

**Comment by shreyajn** [comment]
@kristojorg

**Comment by kristojorg** [comment]
Ok this is what it will be in the end?

**Comment by shreyajn** [comment]
Yes I'll make sure I ask for these and return these from backend. Thank you
